import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import {
  Box,
  Button,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
} from "@mui/material";
import router from "next/router";
import { USER_SEARCH_URL } from "./api";
import { TUserFecthing } from "./api/typeSchema";

export default function Home() {
  const [users, setUsers] = useState<TUserFecthing>();
  console.log(users);
  useEffect(() => {
    const fetchUsers = async () => {
      try {
        const response = await axios.get(USER_SEARCH_URL);
        setUsers(response.data);
      } catch (error) {
        console.error("Error fetching users:", error);
      }
    };

    fetchUsers();
  }, []);

  // const handleDelete = async (userId: string) => {
  //   try {
  //     await axios.delete(
  //       `https://training-mssql-expressjs.app.mapboss.co.th/user/${userId}`
  //     );
  //     setUsers((prevUsers) => prevUsers.filter((user) => user.id !== userId));
  //   } catch (error) {
  //     console.error("Error deleting user:", error);
  //   }
  // };

  return (
    <>
      <Head>
        <title>Mapboss Web Development</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ p: "2rem" }}>
        <Table sx={{ border: 0.5 }}>
          <TableHead>
            <TableRow>
              <TableCell>First name</TableCell>
              <TableCell>Last name</TableCell>
              <TableCell>Username</TableCell>
              <TableCell>Email</TableCell>
              <TableCell>Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {users?.data?.map((user) => (
              <TableRow key={user.id}>
                <TableCell>{user.firstName}</TableCell>
                <TableCell>{user.lastName}</TableCell>
                <TableCell>{user.username}</TableCell>
                <TableCell>{user.email}</TableCell>
                <TableCell>
                  <Box sx={{ gap: "2rem" }}>
                    <Button
                      sx={{mr: '1rem'}}
                      variant="contained"
                      onClick={() => router.push(`/users/${user.id}`)}
                    >
                      Edit
                    </Button>
                    <Button
                      variant="outlined"
                      color="error"
                      onClick={() => handleDelete(user.id)}
                    >
                      Delete
                    </Button>
                  </Box>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Box>
    </>
  );
}
